[build]
  functions = "src/functions"

[dev] #edited port
  port = 5011

[[redirects]]
  from = "/"
  to = "/.netlify/functions/repositories"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
